# permissions for end users to edit numbers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: number-editor-role
rules:
- apiGroups:
  - rnd.rnd.glrf.xyz
  resources:
  - numbers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rnd.rnd.glrf.xyz
  resources:
  - numbers/status
  verbs:
  - get
